version: '3'

services:

  bench:
    build:
      context: .
      dockerfile: ./runner/Dockerfile
    environment:
      - CODESPEED_PASSWORD=password
    volumes:
      - .:/code

      # You may need to change the source of this mount to a directory on your
      # host machine that contains a synced datadir.
      - /data/bitcoin_bench:/data/bitcoin_bench
      # - /data/bitcoin_pruned_500k:/data/bitcoin_pruned_500k
      - /data/bitcoinperf:/root/.bitcoinperf

  codespeed:
    build:
      context: ./codespeed
    ports:
      - "8000:8000"
    environment:
      TESTING: 1
      DEBUG: 1
      DATABASE_URL: "postgres://codespeed:foobar00@psql:5432/codespeed"
    links:
      - psql

  psql:
    image: docker.io/library/postgres:10
    environment:
      POSTGRES_USER: codespeed
      POSTGRES_PASSWORD: foobar00
    volumes:
      - .:/data
