{
 "title": "Overview",
 "time": { "from": "now-30d", "to": "now" },
 "panels": [
  {
   "title": "Welcome to bitcoinperf",
   "type": "text",
   "gridPos": { "h": 6, "w": 12, "x": 0, "y": 0 },
   "content": "This site hosts benchmarking results for the Bitcoin Core project.\n\nThe goal is to keep tabs on various important, high-level metrics like initial block download \nand reindex time, build duration/memory usage, and test suite duration. It is maintained\nby @jamesob and @MarcoFalke.\n\nThe code for this site is available on [Github](https://github.com/chaincodelabs/bitcoinperf).\n\nA slightly uglier (but more detailed) [codespeed interface is available here](https://codespeed.bitcoinperf.com)."
  },
  {
   "title": "Last functional test length (gcc)",
   "type": "singlestat",
   "gridPos": { "h": 3, "w": 6, "x": 12, "y": 0 },
   "format": "dtdurations",
   "valueName": "current",
   "targets": [
    {
     "rawSql": "SELECT\n  date AS \"time\",\n  value\nFROM all_result\nWHERE\n  $__timeFilter(date) AND\n  bench_name = 'functionaltests.gcc' AND\n  env_name = 'ccl-bench-hdd-1'\nORDER BY 1"
    }
   ]
  },
  {
   "title": "Last gcc build length (j=1)",
   "type": "singlestat",
   "gridPos": { "h": 3, "w": 6, "x": 18, "y": 0 },
   "format": "dtdurations",
   "valueName": "current",
   "targets": [
    {
     "rawSql": "SELECT\n  date AS \"time\",\n  value\nFROM all_result\nWHERE\n  $__timeFilter(date) AND\n  bench_name = 'build.make.1.gcc' AND\n  env_name = 'ccl-bench-hdd-1'\nORDER BY 1"
    }
   ]
  },
  {
   "title": "Last IBD to 522,000 (HDD, dbcache=2048)",
   "type": "singlestat",
   "gridPos": { "h": 3, "w": 12, "x": 12, "y": 3 },
   "format": "dtdurations",
   "valueName": "current",
   "targets": [
    {
     "rawSql": "SELECT\n  date AS \"time\",\n  value\nFROM all_result\nWHERE\n  $__timeFilter(date) AND\n  bench_name = 'ibd.local.522000.dbcache=2048' AND\n  env_name = 'ccl-bench-hdd-1'\nORDER BY 1"
    }
   ]
  },
  {
   "title": "Initial block download to height 522,000 from a local peer",
   "type": "graph",
   "gridPos": { "h": 6, "w": 24, "x": 0, "y": 6 },
   "yaxes": [
    { "format": "s" }
   ],
   "targets": [
    {
     "rawSql": "SELECT\n  date AS \"time\",\n  value AS \"4x Intel Xeon CPU E3-1220 v5 @ 3.00GHz | SSD | 8GB | Debian 9.4\"\nFROM ibd_result\nWHERE\n  $__timeFilter(date) AND\n  height = '522000' AND\n  env_name = 'ccl-bench-ssd-6' AND\n  type = 'local'\nORDER BY 1"
    },
    {
     "rawSql": "SELECT\n  date AS \"time\",\n  value AS \"4x Intel Xeon CPU E3-1220 v5 @ 3.00GHz | HDD | 8GB | Debian 9.4\"\nFROM ibd_result\nWHERE\n  $__timeFilter(date) AND\n  height = '522000' AND\n  env_name = 'ccl-bench-hdd-1' AND\n  type = 'local'\nORDER BY 1"
    }
   ]
  },
  {
   "title": "Initial block download to height 522,000 from a local peer (memory usage)",
   "type": "graph",
   "gridPos": { "h": 6, "w": 24, "x": 0, "y": 12 },
   "yaxes": [
    { "format": "kbytes" }
   ],
   "targets": [
    {
     "rawSql": "SELECT\n  date AS \"time\",\n  value AS \"4x Intel Xeon CPU E3-1220 v5 @ 3.00GHz | SSD | 8GB | Debian 9.4\"\nFROM ibd_memusage_result\nWHERE\n  $__timeFilter(date) AND\n  env_name = 'ccl-bench-ssd-6' AND\n  height = '522000'\nORDER BY 1"
    },
    {
     "rawSql": "SELECT\n  date AS \"time\",\n  value AS \"4x Intel Xeon CPU E3-1220 v5 @ 3.00GHz | HDD | 8GB | Debian 9.4\"\nFROM ibd_memusage_result\nWHERE\n  $__timeFilter(date) AND\n  env_name = 'ccl-bench-hdd-1' AND\n  height = '522000'\nORDER BY 1"
    }
   ]
  },
  {
   "title": "Reindex to height 522,000",
   "type": "graph",
   "gridPos": { "h": 5, "w": 24, "x": 0, "y": 18 },
   "yaxes": [
    { "format": "s" }
   ],
   "targets": [
    {
     "rawSql": "SELECT\n  date AS \"time\",\n  value AS \"4x Intel Xeon CPU E3-1220 v5 @ 3.00GHz | SSD | 8GB | Debian 9.4\"\nFROM reindex_result\nWHERE\n  $__timeFilter(date) AND\n  height = '522000' AND\n  env_name = 'ccl-bench-ssd-6'\nORDER BY 1"
    },
    {
     "rawSql": "SELECT\n  date AS \"time\",\n  value AS \"4x Intel Xeon CPU E3-1220 v5 @ 3.00GHz | HDD | 8GB | Debian 9.4\"\nFROM reindex_result\nWHERE\n  $__timeFilter(date) AND\n  height = '522000' AND\n  env_name = 'ccl-bench-hdd-1'\nORDER BY 1"
    }
   ]
  },
  {
   "title": "Reindex to height 522,000 (memory usage)",
   "type": "graph",
   "gridPos": { "h": 5, "w": 24, "x": 0, "y": 23 },
   "yaxes": [
    { "format": "kbytes" }
   ],
   "targets": [
    {
     "rawSql": "SELECT\n  date AS \"time\",\n  value AS \"4x Intel Xeon CPU E3-1220 v5 @ 3.00GHz | SSD | 8GB | Debian 9.4\"\nFROM reindex_memusage_result\nWHERE\n  $__timeFilter(date) AND\n  height = '522000' AND\n  env_name = 'ccl-bench-ssd-6'\nORDER BY 1"
    },
    {
     "rawSql": "SELECT\n  date AS \"time\",\n  value AS \"4x Intel Xeon CPU E3-1220 v5 @ 3.00GHz | HDD | 8GB | Debian 9.4\"\nFROM reindex_memusage_result\nWHERE\n  $__timeFilter(date) AND\n  height = '522000' AND\n  env_name = 'ccl-bench-hdd-1'\nORDER BY 1"
    }
   ]
  }
 ]
}