---
# The configuration file run for bitcoinperf.com's live site.

compilers:
  - gcc
  - clang

synced_peer:
  datadir: /home/ccl/bitcoin_bench_data
  repodir: /home/ccl/bitcoin
  bitcoind_extra_args: ''

codespeed:
  url: "https://codespeed.bitcoinperf.com"
  username: james
  password: "${CODESPEED_PASSWORD}"

slack:
  webhook_url: "${SLACK_WEBHOOK_URL}"

benches:
  # unittests:
  #   num_jobs: 3

  # functests:
  #   num_jobs: 1

  microbench:
    enabled: true

  ibd_from_local:
    run_count: 1
    stash_datadir: /tmp/datadir
    time_heights:
      - 522_000
      - 650_000
      - 750_000
    end_height: 750_000

  reindex:
    # Restash the datadir once we're done indexing so we can run
    # reindex_chainstate.
    stash_datadir: /tmp/datadir
    src_datadir: /tmp/datadir
    time_heights:
      - 522_000
      - 650_000
      - 750_000
    end_height: 750_000

  reindex_chainstate:
    src_datadir: /tmp/datadir
    time_heights:
      - 522_000
      - 650_000
      - 750_000
    end_height: 750_000


to_bench:
  - gitref: master
    bitcoind_extra_args: '-dbcache=2048 -prune=10000'
